angelanew/angelanew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

angelanew/blog/urls.py
from django.urls import path

from . import views 

app_name = "blog"

urlpatterns = [
	path('', views.listar_noticias, name="listar_noticias"),
	path('<int:id_noticia>/', views.ver_noticias, name="ver_noticias")
]

angelanew/blog/models.py
from django.db import models

#Create your models here.

class Noticia(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.CharField(max_length=1000)
	fecha_pub = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s" % (self.titulo, self.fecha_pub)

angelanew/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

#MVT
#Models
#View
#Template
#Importacion de Librerias Personales
from . import models


def listar_noticias(request):
	"""
		Obtiene las noticias de la base de datos

		Retorna:
			El listado de las noticias
	"""
	#Obtiene el listado de todas las noticias
	#De la base de datos y la asigna a la variable
	#noticias
	noticias = models.Noticia.objects.all()

	#Retorna todo renderizado para ser leido en el
	#explorador, tiene tres parametros
	#Solicitud(request), plantilla de datos y datos
	return render(
					request,
					'./noticias/index.html', 
					{'news':noticias}
				)



def ver_noticias(request, id_noticia):
	"""
		Obtiene una noticia de la base de datos

		Parametros:
			id_noticia es numerico y hace referencia
			al identificador de la noticia buscada

		Retorna:
			la noticia buscada si existe
	"""

	noticia = models.Noticia.objects.get(id=id_noticia)

	return render(
					request,
					'./noticias/detalle.html',
					{'noticia':noticia}
				)

angelanew/blog/templates/noticias/detalle.html
<!-- Extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}


{% block titulo %}
	{{ noticia.titulo }}
{% endblock %}


<!--
	Pasa la informacion que va ser mostrada en el bloque
	informacion de la pagina base.html
-->
	{% block informacion %}

		<h1>{{ noticia.titulo }}</h1>

		<p>{{ Noticia.descripcion }}</p>
		<div class="text-secondary">
			Publicacion: {{ noticia.fecha_pub }}
		</div>
	{% endblock %}

angelanew/blog/templates/noticias/index.html
<!-- Extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}

<!--
	Pasa la informacion que va ser mostrada en el bloque
	informacion de la pagina base.html
-->
{% block informacion %}
		{% for new in news %}
			<div class="p-1">
				<h2 class="text-dark">
					<a href="{% url 'blog:ver_noticias' new.id %}">
						{{ new.titulo }}
					</a>
				<hr>
				<p>{{ new.descripcion }}</p>
				<a href="{% url 'blog:ver_noticias' new.id %}">
					Ver...
				</a>

			</div>
		{% endfor %}
		{% endblock %}